app:
  restart: always
  build: ./app
  expose:
    - "8000"
  volumes:
    - ./app:/usr/src/app
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - ENV=DEV

web:
  restart: always
  build: ./web/
  ports:
    - "80:80"
  volumes_from:
    - app
  links:
    - app:app